# Exported AdGuard Home configuration
dns:
  bind_host: "0.0.0.0"
  port: 53
  upstream_dns:
    - "192.168.1.*:5335"
  dnssec: true
  cache_enabled: true
  parallel_upstreams: false

clients: []
filters: []
